
/*EMPLOYEES 테이블에서 사원의 매니저 이름, 사원의 이름 조회, 매니저가 없는 사원은 본인이 매니저임을 표시*/
SELECT * FROM EMPLOYEES E1
JOIN EMPLOYEES E2
ON E1.EMPLOYEE_ID = E2.MANAGER_ID;



/*EMPLOYEES에서 부서별 매니저와 부서별 사원 조회*/
SELECT E1.DEPARTMENT_ID, E1.JOB_ID, E1.LAST_NAME || E1.FIRST_NAME "MANAGER_NAME" FROM EMPLOYEES E1
RIGHT OUTER JOIN EMPLOYEES E2
ON E1.EMPLOYEE_ID = E2.MANAGER_ID
ORDER BY DEPARTMENT_ID;
 
SELECT E.DEPARTMENT_ID, DEPARTMENT_NAME, E.LAST_NAME || E.FIRST_NAME "MANAGER_NAME"
   FROM DEPARTMENTS D JOIN EMPLOYEES E
   ON D.MANAGER_ID = E.EMPLOYEE_ID;


SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT E.DEPARTMENT_ID, E.LAST_NAME || E.FIRST_NAME "EMPLOYEE_NAME" FROM
(
   SELECT E1.DEPARTMENT_ID, E1.EMPLOYEE_ID, E1.LAST_NAME || E1.FIRST_NAME "MAGER" FROM EMPLOYEES E1
	JOIN EMPLOYEES E2
	ON E1.EMPLOYEE_ID = E2.MANAGER_ID
)E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;



/*EMPLOYEES에서 각 사원별로 관리부서(매니저)와 소속부서(사원) 조회*/
SELECT E2.LAST_NAME, E1.JOB_ID, E2.JOB_ID FROM
(
   SELECT JOB_ID, MANAGER_ID 
   FROM EMPLOYEES
   GROUP BY JOB_ID, MANAGER_ID
) E1 
FULL OUTER JOIN EMPLOYEES E2
ON E1.MANAGER_ID = E2.EMPLOYEE_ID
ORDER BY E2.LAST_NAME;

  SELECT JOB_ID, MANAGER_ID 
   FROM EMPLOYEES
   GROUP BY JOB_ID, MANAGER_ID
  ORDER BY MANAGER_ID;


